### ISSUE TITLE
Split person for David Lawrence Miller

### ISSUE THREAD

**Issue by jasonpriem** [Impactstory/depsy#1]
Has three different persons in the DB. See https://twitter.com/millerdl/status/663818098475196416 for URLs.

**Comment by hpiwowar** [comment]
http://depsy.org/person/333208  
http://depsy.org/person/438045  
http://depsy.org/person/435249

**Comment by hpiwowar** [comment]
Fixed :)
Here's the merged profile:  http://depsy.org/person/333208
