### ISSUE TITLE
Multiple versions of Gavin L. Simpson

### ISSUE THREAD

**Issue by gavinsimpson** [Impactstory/depsy#13]
Depsy has picked up two versions of me (one my github username and the other how I refer to myself in R packages):

1. R package author version http://depsy.org/person/433295
2. github user/account http://depsy.org/person/330174

If you could combine these, that'd be great.

If needed, my ORCID iD is: [0000-0002-9084-8413](https://orcid.org/0000-0002-9084-8413)

TIA

**Comment by EDiLD** [comment]
Same here for me:

1. Eduard Szoecs http://depsy.org/person/436081
2. Eduard Szöcs http://depsy.org/person/330190

My ORDIC ID: http://orcid.org/0000-0001-5376-1194

This seems also to be an issue with Umlauts/Diaeresis (oe / ö, ue / ü). See also the authors of the webchem package [here](http://depsy.org/package/r/webchem).

**Comment by hpiwowar** [comment]
All fixed!  

Gavin:  http://depsy.org/person/330174
Eduard:  http://depsy.org/person/330190
all webchem:  http://depsy.org/package/r/webchem

Yeah, we don't have automated ways to deduplicate Umlauts/Diaeresis with the non-Umlauted version of names alas, but we can deal with them on a per-person basis.  

Thanks for reporting these so we could fix them!
