### ISSUE TITLE
Astroquery should be research software

### ISSUE THREAD

**Issue by jasonpriem** [Impactstory/depsy#14]
http://depsy.org/package/python/astroquery

https://twitter.com/j_t_allen/status/664279600940253184

**Comment by hpiwowar** [comment]
Fixed!  97th percentile :)

**Comment by bsipocz** [comment]
@hpiwowar - The contributor list is also seems problematic for astroquery (among others). It may be related to #16; or user "ube" is just a known placeholder for the time being?

**Comment by hpiwowar** [comment]
yeah, that is a bug!  thanks for letting us know.  opening as a new ticket: https://github.com/Impactstory/depsy/issues/24
