### ISSUE TITLE
CRAN link on landing page

### ISSUE THREAD

**Issue by sckott** [Impactstory/depsy#18]
On the landing page here 

<img width="916" alt="screen shot 2015-11-13 at 9 39 07 am" src="https://cloud.githubusercontent.com/assets/577668/11152934/6e8f374c-89ea-11e5-8051-1c5b0c4b2917.png">

Pypi links to where you can find packages, but the link for CRAN goes to the R project landing page. Perhaps link to https://cran.rstudio.com/web/packages/, which seems closer match to the pypi link

Or, there's also http://www.r-pkg.org/ - a 3rd party R pkg UI that's not based on 1990's best practice from @gaborcsardi

**Comment by sckott** [comment]
:)

**Comment by jasonpriem** [comment]
It's not 1990s best practice, it's vintage, man. #hipstercode.

**Comment by sckott** [comment]
oh right, that
