### ISSUE TITLE
Mark IPython as research software.

### ISSUE THREAD

**Issue by Carreau** [Impactstory/depsy#19]
http://depsy.org/package/python/ipython is not marked as research, 
can you mark it ?

Would be happy to send a PR if it helps, but not sure how.

Thanks,

**Comment by hpiwowar** [comment]
fixed :)

http://depsy.org/package/python/ipython

**Comment by Carreau** [comment]
Thanks a lot ! Is there anything to make your life easier if I find more ? Like write a SQL query you guys just have to copy/past  !

Thanks !

**Comment by hpiwowar** [comment]
Nope!  just make a github ticket and include its Depsy url, that's awesome.  Thanks :)
