### ISSUE TITLE
'did we guess wrong?' leads to twitter

### ISSUE THREAD

**Issue by goldingn** [Impactstory/depsy#2]
it should probably lead here

**Comment by jasonpriem** [comment]
Yeah, that makes sense. But were worried that many folks won't have experience with GitHub system...in those cases, tweeting likely an easier way to get feedback heard. Maybe we could include links to both Twitter and GitHub?

**Comment by goldingn** [comment]
Yup that sounds like good approach. I expect a lot of the people vanity searching (like I was) will have accounts & would rather give details here. Is there another route for people without github or twitter?

**Comment by Carreau** [comment]
I think it would be good to have a FAQ page with things like:

 - What do I do if my software is not correctly categorizes.
 - My Profile is wrong ?

and so on and so forth.

**Comment by jasonpriem** [comment]
@Carreau thanks for the feedback re the FAQ! We'll see how many other people ask for this; till then, we'll try to solve it with better UI and docs from within the app, as I think that's a better UX.
