### ISSUE TITLE
Multiple versions of Zhian Kamvar

### ISSUE THREAD

**Issue by zkamvar** [Impactstory/depsy#22]
As package Author (without M.I.): http://depsy.org/person/438058
As github user (with M.I.): http://depsy.org/person/336921

Can these be merged into Zhian N. Kamvar?

Thanks,
Zhian

**Comment by hpiwowar** [comment]
Fixed!  Merged into this single profile:  http://depsy.org/person/336921

Thanks for reporting it!  :)
