### ISSUE TITLE
lgcp split

### ISSUE THREAD

**Issue by bentaylor1** [Impactstory/depsy#23]
Hi I'm packages maintainer for lgcp, spatsurv, cruts and miscFuncs, however only the last three appear on my profile http://depsy.org/person/338567 and lgcp, appears here http://depsy.org/person/437426 I would be very grateful if you could merge these.

Many thanks

Ben

**Comment by bentaylor1** [comment]
Hi, I've changed my name as it appears on lgcp to Benjamin M. Taylor. Hoping this helps!

**Comment by hpiwowar** [comment]
Fixed!  Merged into a single profile here:  http://depsy.org/person/338567

Thanks for reporting it :)
