### ISSUE TITLE
Multiple versions of Barry Rowlingson

### ISSUE THREAD

**Issue by barryrowlingson** [Impactstory/depsy#6]
These are all me:

http://depsy.org/person/437428
http://depsy.org/person/331413
http://depsy.org/person/334287
http://depsy.org/person/440888

I also seem to collaborate with myself on several things:

http://depsy.org/package/r/geonames
  "geonames by Rowlingson, Rowlingson, Ram, and 2 others "

Best of luck cleaning your database!

**Comment by hpiwowar** [comment]
thanks barry!  will work to fix asap and let you know.

**Comment by hpiwowar** [comment]
Fixed!  Here's your single merged profile: http://depsy.org/person/334287  
Thanks for letting us know about the problem!
