### ISSUE TITLE
ADS citation search link broken

### ISSUE THREAD

**Issue by scls19fr** [Impactstory/depsy#64]
Hellon,

ADS citation search link is broken
see for example http://depsy.org/package/python/windrose
Based on term searches in [ADS (1)](http://labs.adsabs.harvard.edu/adsabs/search/?q=(%20(=%22import%20windrose%22%20OR%20=%22github%20com%20windrose%22%20OR%20=%22pypi%20python%20org%20windrose%22%20OR%20=%22available%20in%20the%20windrose%20project%22%20OR%20=%22windrose%20a%20community-developed%22%20OR%20=%22library%20windrose%22%20OR%20=%22libraries%20windrose%22%20OR%20=%22package%20windrose%22%20OR%20=%22packages%20windrose%22%20OR%20=%22windrose%20package%22%20OR%20=%22windrose%20packages%22%20OR%20=%22windrose%20library%22%20OR%20=%22windrose%20libraries%22%20OR%20=%22windrose%20python%22%20OR%20=%22windrose%20software%22%20OR%20=%22windrose%20api%22%20OR%20=%22windrose%20coded%22%20OR%20=%22windrose%20new%20open-source%22%20OR%20=%22windrose%20open-source%22%20OR%20=%22open%20source%20software%20windrose%22%20OR%20=%22windrose%20modeling%20frameworks%22%20OR%20=%22windrose%20modeling%20environment%22%20OR%20=%22modeling%20framework%20windrose%22%20OR%20=%22windrose:%20sustainable%20software%22%20OR%20=%22windrose%20component-based%20modeling%20framework%22)%20-author:%22windrose%22)&year_from=1997&month_to=&year_to=2016)

It raises an HTTP error code 500 (Internal Server Error) and displays

WARNING: this service will be deprecated in the coming months.
Please consider using [ADS Classic or Bumblebee](http://ads.harvard.edu/)

Error! Search service error: Error communicating with search service
Well, this is embarrassing.
The application has generated an error.
We logged the error and we will read it soon, but if you want us to know about it immediately, please send us an email.

Please, be patient with this application: it's still in "alpha" stage. We are working hard on making improvements.

Kind regards

**Comment by hpiwowar** [comment]
Fixed!  Thanks a lot for the bug report :)
