### ISSUE TITLE
merge Thomas Robitaille

### ISSUE THREAD

**Issue by hpiwowar** [Impactstory/depsy#7]
same person:

depsy.org/person/442125 
depsy.org/person/330590 

reported by @astrofrog [on twitter](https://twitter.com/astrofrog/status/664141439463464960)

**Comment by astrofrog** [comment]
Ah and this one is me too! http://depsy.org/person/430783

**Comment by hpiwowar** [comment]
cool, thanks.

**Comment by astrofrog** [comment]
Not sure if you also link to ORCID IDs, but if so, mine is 0000-0002-8642-1329

**Comment by hpiwowar** [comment]
Fixed!  Here's the merged profile:  http://depsy.org/person/330590
Thanks :)

**Comment by astrofrog** [comment]
@hpiwowar - thanks!
